export default [
  {
    type: 'physical',
    reference: '1',
    name: 'Classic Low Bridge Sunglasses',
    color: 'White',
    size: 'Small',
    imgSrc: '/sunglasses2-min.jpg',
    quantity: 0,
    quantity_unit: 'pcs',
    unit_price: 25000,
    tax_rate: 2500,
  },
  {
    type: 'physical',
    reference: '2',
    name: 'Original Canvas Slip-On',
    color: 'Black and White',
    size: '39',
    imgSrc: '/shoe1-min.jpg',
    quantity: 0,
    quantity_unit: 'pcs',
    unit_price: 50000,
    tax_rate: 2500,
  },
  {
    type: 'physical',
    reference: '3',
    name: 'Round neck organic t-shirt',
    color: 'White',
    size: 'Small',
    imgSrc: '/t-shirt.jpg',
    quantity: 0,
    quantity_unit: 'pcs',
    unit_price: 34000,
    tax_rate: 2500,
  },
]
